name: shs108private
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"
# environment:
#   sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: 4.3.8
  google_fonts: ^2.1.0
  flutter_form_builder: ^7.0.0-beta.0
  form_builder_extra_fields: ^7.0.0-alpha.6
  form_builder_validators: ^7.0.0
  dropdown_search: ^0.6.3
  # device_preview: ^0.7.4
  responsive_framework: ^0.1.4
  progress_state_button: ^1.0.3
  image_picker: ^0.8.4+4
  image_cropper: ^1.4.1
  rounded_expansion_tile: ^0.0.13
  path: ^1.8.0
  dio: ^4.0.1
  sizer: ^2.0.15
  table_calendar: ^3.0.3
  latlng: ^0.1.0
  map: ^1.0.0
  get_storage: ^2.0.3
  checkbox_grouped: ^1.7.1
  flutter_svg: ^0.22.0
  printing: ^5.6.6
  geolocator: ^7.7.1
  double_back_to_close: ^2.0.0
  dartz: ^0.10.1
  animated_text_kit: ^4.2.1
  path_provider: ^2.0.7
  syncfusion_flutter_pdf: ^19.3.59-beta
  open_file: ^3.2.1
  screenshot: ^1.2.3
  widget_circular_animator: ^1.0.0
  cached_network_image: ^3.2.0
  # youtube_player_flutter: ^8.0.0
  carousel_slider: ^4.0.0
  syncfusion_flutter_maps: ^19.4.43-beta
  font_awesome_flutter: ^9.2.0
  intl: ^0.17.0
  flutter_launcher_icons: ^0.9.1
  connectivity_plus: ^2.2.1

dependency_overrides:
  dropdown_search: ^2.0.1

dev_dependencies:
  flutter_lints: ^1.0.0
  lints: ^1.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    # general for two apps
    - assets/general_for_two_apps/splash_SC/favicon.png
    - assets/general_for_two_apps/splash_SC/logo1.png
    - assets/general_for_two_apps/splash_SC/header.png
    - assets/general_for_two_apps/splash_SC/footer.png
    - assets/general_for_two_apps/splash_SC/title.png
    - assets/general_for_two_apps/splash_SC/subtitle.png

    - assets/general_for_two_apps/shared/defaultAvatar.jpg
    - assets/general_for_two_apps/shared/placeholder_image.jpg

    - assets/general_for_two_apps/phar profile/1.jpg
    - assets/general_for_two_apps/phar profile/2.jpg
    - assets/general_for_two_apps/phar profile/3.JPG

    - assets/general_for_two_apps/sign_in/login-banner.png
    - assets/general_for_two_apps/empty_screens/not_found.svg
    - assets/general_for_two_apps/home_screen/ad.jpg
    - assets/general_for_two_apps/home_screen/ad2.jpg

    - assets/general_for_two_apps/categories/lab-PlaceHolder.jpg
    - assets/general_for_two_apps/categories/biomedical.jpg

    - assets/general_for_two_apps/categoriesIcons/medicalSupplies.svg
    - assets/general_for_two_apps/categoriesIcons/medicative.svg
    - assets/general_for_two_apps/categoriesIcons/pharmacy.svg
    - assets/general_for_two_apps/categoriesIcons/servicesOutside.svg
    - assets/general_for_two_apps/categoriesIcons/suppliesOrganizations.svg
    - assets/general_for_two_apps/categoriesIcons/doctor.jpg
    - assets/general_for_two_apps/categoriesIcons/pharmacy.jpg
    - assets/general_for_two_apps/categoriesIcons/servicesOutside.jpg
    - assets/general_for_two_apps/categoriesIcons/suppliesOrganizations.jpg
    - assets/general_for_two_apps/categoriesIcons/appbarBackground.png
    - assets/general_for_two_apps/categoriesIcons/ambulance.jpg
    - assets/general_for_two_apps/categoriesIcons/remedialTraining.jpg
    - assets/general_for_two_apps/categoriesIcons/humanitarianCases.jpg
    - assets/general_for_two_apps/categoriesIcons/medicalSupplies2.jpg
    - assets/general_for_two_apps/categoriesIcons/hospital2.jpg
    - assets/general_for_two_apps/categoriesIcons/drugs.jpg
    - assets/general_for_two_apps/categoriesIcons/staff.jpg
    - assets/general_for_two_apps/categoriesIcons/healthInsurance.jpg
    - assets/general_for_two_apps/categoriesIcons/remedialTraining.svg
    - assets/general_for_two_apps/categoriesIcons/humanitarianCases.svg
    - assets/general_for_two_apps/categoriesIcons/drugs.svg

    - assets/general_for_two_apps/selectsIcons/serviceIcon.svg
    - assets/general_for_two_apps/selectsIcons/specializationIcon.svg
    - assets/general_for_two_apps/selectsIcons/building.svg
    - assets/general_for_two_apps/selectsIcons/date.svg

    - assets/general_for_two_apps/categoriesIcons/labs.svg

    - assets/general_for_two_apps/categoriesIcons/doctor.svg
    - assets/general_for_two_apps/categoriesIcons/hospital.svg

    - assets/general_for_two_apps/categoriesIcons/hospital.jpg
    - assets/general_for_two_apps/categoriesIcons/labs.jpg
    - assets/general_for_two_apps/categoriesIcons/medicalSupplies.jpg
    - assets/general_for_two_apps/categoriesIcons/medicative.jpg

    - assets/general_for_two_apps/new_categories_images/1-medical-clinics.jpg
    - assets/general_for_two_apps/new_categories_images/2-pharmacies.jpg
    - assets/general_for_two_apps/new_categories_images/3-labs.jpg
    - assets/general_for_two_apps/new_categories_images/4-hospitals-and-health-centers.jpg
    - assets/general_for_two_apps/new_categories_images/5-pharmaceutical.jpg
    - assets/general_for_two_apps/new_categories_images/6-medical-products.jpg
    - assets/general_for_two_apps/new_categories_images/7-medical-supplies.jpg
    - assets/general_for_two_apps/new_categories_images/8-medical-and-humanitarian-associations.jpg
    - assets/general_for_two_apps/new_categories_images/9-remedial-training-services.jpg
    - assets/general_for_two_apps/new_categories_images/10-supply-companies-and-offices.jpg
    - assets/general_for_two_apps/new_categories_images/11-medical-services-outside-Iraq.jpg
    - assets/general_for_two_apps/new_categories_images/12-humanitarian-cases.jpg
    - assets/general_for_two_apps/new_categories_images/13-health-staff.jpg
    - assets/general_for_two_apps/new_categories_images/14-health-insurance-companies.jpg
    - assets/general_for_two_apps/new_categories_images/15-storehouses-and-scientific-offices.jpg
    - assets/general_for_two_apps/new_categories_images/hospital_gov.jpg
    - assets/general_for_two_apps/new_categories_images/16.jpg

    # not done as reuseable
    - assets/general_for_two_apps/icons/date.svg
    - assets/general_for_two_apps/icons/hospital-1066.svg
    - assets/general_for_two_apps/icons/team.svg
    - assets/general_for_two_apps/icons/address.svg
    - assets/general_for_two_apps/icons/stethoscope.svg
    - assets/general_for_two_apps/icons/event.svg

    # not done as reuseable
    - assets/general_for_two_apps/news/news-1.jpg
    - assets/general_for_two_apps/news/news-2.jpg
    - assets/general_for_two_apps/news/news-3.jpg
    - assets/general_for_two_apps/news/news-4.jpg

    # not done as reuseable
    - assets/general_for_two_apps/articals/article-1.jpg
    - assets/general_for_two_apps/articals/article-2.jpg
    - assets/general_for_two_apps/articals/article-3.jpg
    - assets/general_for_two_apps/articals/article-4.jpg

    # not done as reuseable
    - assets/general_for_two_apps/partners/partner-1.jpg
    - assets/general_for_two_apps/partners/partner-2.jpeg
    - assets/general_for_two_apps/partners/partner-3.png
    - assets/general_for_two_apps/partners/partner-4.png

    # not done as reuseable
    - assets/general_for_two_apps/doctors/doc1.jfif
    - assets/general_for_two_apps/doctors/doc2.jfif
    - assets/general_for_two_apps/doctors/doc3.jfif
    - assets/general_for_two_apps/doctors/doc4.jfif
    - assets/general_for_two_apps/doctors/doc5.jfif
    - assets/general_for_two_apps/doctors/doc6.jfif

    # not done as reuseable
    - assets/general_for_two_apps/labs/lab-1.jpg
    - assets/general_for_two_apps/labs/lab-2.jpg
    - assets/general_for_two_apps/labs/lab-3.jpg
    - assets/general_for_two_apps/labs/lab-4.jpg
    - assets/general_for_two_apps/labs/lab-5.jpg
    - assets/general_for_two_apps/labs/lab-6.jpg

    # not done as reuseable
    - assets/general_for_two_apps/hospitals/hos-1.jpg
    - assets/general_for_two_apps/hospitals/hos-2.jpg
    - assets/general_for_two_apps/hospitals/hos-3.jpg
    - assets/general_for_two_apps/hospitals/hos-4.jpg
    - assets/general_for_two_apps/hospitals/hos-5.jpg
    - assets/general_for_two_apps/hospitals/hos-6.jpg

    # not done as reuseable
    - assets/general_for_two_apps/pharmacy items/ph-1.jpg
    - assets/general_for_two_apps/pharmacy items/ph-2.jpg
    - assets/general_for_two_apps/pharmacy items/ph-3.jpg
    - assets/general_for_two_apps/pharmacy items/ph-4.jpg
    - assets/general_for_two_apps/pharmacy items/ph-5.jpg
    - assets/general_for_two_apps/pharmacy items/ph-6.jpg

    # not done as reuseable
    - assets/general_for_two_apps/humanitirian-case-items/humanitarian-case-1.png
    - assets/general_for_two_apps/humanitirian-case-items/humanitarian-case-2.jpg

    # not done as reuseable
    - assets/general_for_two_apps/therapeutic-training-services items/therapeutic-training-services-2.jpg
    - assets/general_for_two_apps/therapeutic-training-services items/therapeutic-training-services-3.jpg
    - assets/general_for_two_apps/therapeutic-training-services items/med-outside.jpg

    # not done as reuseable
    - assets/general_for_two_apps/health-insurance/insur-1.jpg
    - assets/general_for_two_apps/health-insurance/privateClinics.jpg

    # not done as reuseable
    - assets/general_for_two_apps/MedicalAndHumanitarianSocieties/2.jpg

    # not done as reuseable
    - assets/general_for_two_apps/ScientificBureau/1.jpg
    - assets/general_for_two_apps/ScientificBureau/mathakher.jpg

    # not done as reuseable
    - assets/general_for_two_apps/MedicalAndHumanitarianSocieties/ensanea.jpg

    # not done as reuseable
    - assets/general_for_two_apps/news-bar/news-5.jpg
    - assets/general_for_two_apps/news-bar/news-6.jpg
    - assets/general_for_two_apps/news-bar/news-7.jpg
    - assets/general_for_two_apps/news-bar/enjoy doing news bar.png

    # for only providers app
    - assets/onle_for_second_app/providers_icon/favicon+.png
    - assets/onle_for_second_app/doctor/doctorSignIn.jpg
    - assets/onle_for_second_app/doctor/doctorSignUp.png

    - assets/onle_for_second_app/professions/10administrators.jpg
    - assets/onle_for_second_app/professions/11life_support.jpg
    - assets/onle_for_second_app/professions/12ambulance_staff.jpg
    - assets/onle_for_second_app/professions/1doctor.jpg
    - assets/onle_for_second_app/professions/2pharmacist.png
    - assets/onle_for_second_app/professions/2pharmacist.jpg
    - assets/onle_for_second_app/professions/3Analyzer.jpg
    - assets/onle_for_second_app/professions/4practitioners.jpg
    - assets/onle_for_second_app/professions/5health_administrator.jpg
    - assets/onle_for_second_app/professions/6medical_technicians.jpg
    - assets/onle_for_second_app/professions/7maintenance_and_operation_technicians.jpg
    - assets/onle_for_second_app/professions/8medical_device_engineers.jpg
    - assets/onle_for_second_app/professions/9biomedical_engineers.jpg
    - assets/onle_for_second_app/professions/hos-5.jpg
    - assets/onle_for_second_app/professions/1doctor.jpg
    - assets/onle_for_second_app/professions/2pharmacist.png
    - assets/onle_for_second_app/professions/3Analyzer.jpg
    - assets/onle_for_second_app/professions/4practitioners.jpg
    - assets/onle_for_second_app/professions/5health_administrator.jpg
    - assets/onle_for_second_app/professions/6medical_technicians.jpg
    - assets/onle_for_second_app/professions/7maintenance_and_operation_technicians.jpg
    - assets/onle_for_second_app/professions/8medical_device_engineers.jpg
    - assets/onle_for_second_app/professions/9biomedical_engineers.jpg
    - assets/onle_for_second_app/professions/10administrators.jpg
    - assets/onle_for_second_app/professions/11life_support.jpg
    - assets/onle_for_second_app/professions/12ambulance_staff.jpg

    # temporary apps
    - assets/temporary_images_for institutions_covers/1.jpg
    - assets/temporary_images_for institutions_covers/2.jpg
    - assets/temporary_images_for institutions_covers/3.jpg
    - assets/temporary_images_for institutions_covers/4.png
    - assets/temporary_images_for institutions_covers/5.jpg

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  # for patients
  # image_path: "assets/general_for_two_apps/splash_SC/favicon.png"
  # for providers
  image_path: "assets/onle_for_second_app/providers_icon/favicon+.png"
